### ISSUE TITLE
Obtaining VROM for Nvidia

### ISSUE THREAD

**Issue by Vlad1mir-D** [jscinoz/optimus-vfio-docs#5]
The easiest way to obtain NVIDIA VROM:
- Install proprietary NVIDIA graphics driver (I used `NVIDIA-Linux-x86_64-430.50.run`)
- Load driver (i.e. `modprobe nvidia_drm`) to initialize GPU
- `echo 1 > /sys/devices/pci0000\:00/0000\:00\:01.0/0000\:01\:00.0/rom`
- `cat /sys/devices/pci0000\:00/0000\:00\:01.0/0000\:01\:00.0/rom > vbios.rom`

That's it!

```
# file vbios.rom 
vbios.rom: BIOS (ia32) ROM Ext. IBM comp. Video (208*512)
```

**Comment by coderobe** [comment]
This does not work on most muxless devices

**Comment by Vlad1mir-D** [comment]
At least it works on MSI GP72 7RD and DELL XP 9570.
